### ISSUE TITLE
Remove all default styling

### ISSUE THREAD

**Issue by terrabythia** [timolins/react-hot-toast#220]
I might be missing something, but I cannot find out how you can remove the default styling, except for overwriting it. What I'm doing now is adding a custom class that resets all styling of the `Toaster` component, like this:

```css
.resetToaster {
  background: transparent !important;
  color: currentColor !important;
  box-shadow: none !important;
  padding: 0 !important;
  border-radius: 0 !important;
}
```

Is there a way to not add the styling in the first place?
