### ISSUE TITLE
Trouble with className

### ISSUE THREAD

**Issue by Android789515** [timolins/react-hot-toast#350]
I'm trying to set up class name:
```tsx
<Toaster
   toastOptions={{
      // Not working
      className: styles.toaster,

      // Not working
      className: 'toaster',

      // Working
      style: {
         background: 'red',
      },
   }}
/>
```

My CSS:
```css
.toaster {
   background: red;
}
```

**Comment by Android789515** [comment]
The issue was specificity.  Overriding default styles can be a pain in CSS modules as you have to override the specificity of the default class.

The current fix, increase specificity:
```css
.toaster.toaster {
   background: red;
}
```
